# Generated by Django 5.1.3 on 2024-12-04 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=100)),
                ('last_edited_date', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'videos',
                'constraints': [models.UniqueConstraint(fields=('id',), name='AK_6')],
            },
        ),
    ]
