# Generated by Django 5.1.4 on 2024-12-08 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=100)),
                ('last_edited_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('order_number', models.SmallIntegerField()),
                ('last_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_socials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_medias',
                'constraints': [models.UniqueConstraint(fields=('id',), name='AK_7'), models.UniqueConstraint(fields=('order_number',), name='unique_order_number')],
            },
        ),
    ]
