# Generated by Django 5.1.4 on 2024-12-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_socialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='order_number',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
