# Generated by Django 5.1.3 on 2024-12-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_video_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
