# Generated by Django 5.1.4 on 2024-12-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_socialmedia_options_alter_socialmedia_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(max_length=100000),
        ),
    ]
