# Generated by Django 5.1.4 on 2024-12-15 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_socialmedia_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('order_number', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('last_edited_date', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['order_number'],
                'constraints': [models.UniqueConstraint(fields=('order_number',), name='unique_section_order')],
            },
        ),
    ]
