# Generated by Django 5.1.4 on 2024-12-15 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TextLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_lines', to='dashboard.section')),
            ],
            options={
                'db_table': 'text_lines',
            },
        ),
    ]
