# Generated by Django 5.1.4 on 2024-12-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_section_content_textline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, default='nothing'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TextLine',
        ),
    ]
