# Generated by Django 5.1.4 on 2024-12-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_section_content_delete_textline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_active',
        ),
    ]
