# Generated by Django 5.1.4 on 2024-12-22 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_section_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.SmallIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='dashboard.section')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['order_number'],
                'constraints': [models.UniqueConstraint(fields=('order_number',), name='unique_service_order')],
            },
        ),
    ]
