# Generated by Django 5.1.4 on 2024-12-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(default='null', max_length=100000),
            preserve_default=False,
        ),
    ]
