# Generated by Django 5.1.4 on 2024-12-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_services_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(),
        ),
    ]
