# Generated by Django 4.2.16 on 2025-01-06 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_section_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order_number', models.SmallIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('logo', models.CharField(max_length=100000)),
                ('last_edited_date', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_brands', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='dashboard.section')),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order_number', models.SmallIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('last_edited_date', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_works', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'works',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='BrandWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.brand')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.work')),
            ],
            options={
                'db_table': 'brands_works',
            },
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.UniqueConstraint(fields=('order_number',), name='unique_work_order'),
        ),
        migrations.AddConstraint(
            model_name='brandwork',
            constraint=models.UniqueConstraint(fields=('brand', 'work'), name='unique_brand_work'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('order_number',), name='unique_brand_order'),
        ),
    ]
