# Generated by Django 4.2.16 on 2025-01-06 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_brand_work_brandwork_work_unique_work_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='dashboard.section'),
        ),
    ]
