# Generated by Django 5.1.4 on 2025-01-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_brand_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='label',
            field=models.CharField(max_length=20),
        ),
    ]
