# Generated by Django 4.2.17 on 2025-01-14 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0015_alter_section_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order_number', models.SmallIntegerField()),
                ('author_name', models.CharField(max_length=30)),
                ('author_surname', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('last_edited_date', models.DateTimeField(auto_now=True)),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.brand')),
                ('last_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_reviews', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.section')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('order_number',), name='unique_review_order'),
        ),
    ]
