# Generated by Django 4.2.17 on 2025-01-14 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_review_review_unique_review_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.brand'),
        ),
        migrations.AlterField(
            model_name='review',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.section'),
        ),
    ]
