# Generated by Django 4.2.17 on 2025-01-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_review_brand_id_alter_review_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='dashboard.section'),
        ),
    ]
