# Generated by Django 4.2.17 on 2025-01-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_brand_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'subscribers',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='img',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_subscriber_email'),
        ),
    ]
