# Generated by Django 4.2.17 on 2025-01-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_subscriber_work_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='img',
            field=models.CharField(max_length=100),
        ),
    ]
